class ApiResponseCodes:

    NO_ASSOCIATED_RESPONSE_CODE = 0

    REGISTRATION_SUCCESSFUL = 100
    REGISTRATION_FAIL_DUPLICATED_ID = 110
    REGISTRATION_FAIL_NO_FACE = 120
    REGISTRATION_FAIL_MULTIPLE_FACES = 121
    REGISTRATION_FAIL_INVALID_BASE64 = 122

    RECKON_SUCCESSFUL = 200
    RECKON_FAIL = 210
    RECKON_FAIL_MULTIPLE_FACES = 220
    RECKON_FAIL_NO_FACES = 221
    RECKON_FAIL_INVALID_BASE_64 = 222

    DELETE_SUCCESSFUL = 500
    DELETE_FAIL = 510
